### ISSUE TITLE
UX: Remove Endpoints on RackN Portal.. Save Button doesent work.. 

### ISSUE THREAD

**Issue by IvanGrischott** [digitalrebar/provision#612]
![endpoint](https://user-images.githubusercontent.com/7550764/34523878-a070e5b8-f099-11e7-93ef-90438201c8fc.jpg)

**Comment by ctrees** [comment]
Well... I think this is the same, but you can't Logout either, so I'm putting here.

**Comment by ctrees** [comment]
I can't seem to re-create the "Support & Logout" not working again.  I wonder if it's cache state related ? just guessing ? .... I'll try a few things to see if I can recreate.

**Comment by zehicle** [comment]
Should be fixed on the backend.  Small tweak on the front end will need a few hours to get into prod.

**Comment by ctrees** [comment]
I just re-tested with no happiness.
(See my closed bug for how I tested... but)
I attempted to clean up some old DRP Endpoints in my RackN UX portal.

Go to https://rackn.github.io/provision-ux/#/org/<mytoken?>/endpoints
Hamburger -> Endpoints
Click "Remove" on an ENDPOINT
Click "Save"
No Effect even after page reload

**Comment by ctrees** [comment]
I got the 'Logout' in that state again (actually relieved as I'm not crazy).. putting some pictures up.

First, I have just logged in, but Login of Create Account ? modal ? is up.

![rackn-ux-bug612-logoutfail-1](https://user-images.githubusercontent.com/2227021/34565042-f5853a92-f11e-11e7-9aea-257847aff6bc.png)

I check to make sure I can get to my account back-end (aka hamburger menu modal)

![rackn-ux-bug612-logoutfail-2](https://user-images.githubusercontent.com/2227021/34565043-f597342c-f11e-11e7-891e-1ed31d6714e6.png)

Clicking the Support & Logout have no effect, I expect the 'LogOut' Support User Screen.

![rackn-ux-bug612-logoutfail-3](https://user-images.githubusercontent.com/2227021/34565044-f5a7e790-f11e-11e7-8328-f4a31b97ebb7.png)

**Comment by ctrees** [comment]
So, I just re-tested with a anon chrome session (make sure null browser cache at start).  The logout issue went away, but the remove endpoint issued is still present.  My 'guess' is my Logout issue is cache timing stuff

**Comment by sygibson** [comment]
needs verification still - and possible improvement

**Comment by galthaus** [comment]
This seems to work now.
